# Generated by Django 4.1.2 on 2022-12-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='registerD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='username')),
                ('email', models.CharField(max_length=200, verbose_name='email')),
                ('password1', models.CharField(max_length=128, verbose_name='password1')),
                ('password2', models.CharField(max_length=128, verbose_name='password2')),
            ],
        ),
        migrations.RenameField(
            model_name='register',
            old_name='name',
            new_name='username',
        ),
    ]
