# Generated by Django 4.1.2 on 2022-12-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_data_age_data_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='age',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
