# Generated by Django 4.1.2 on 2022-12-16 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_docprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocProfile',
        ),
    ]
