# Generated by Django 4.1.2 on 2022-12-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_doc'),
    ]

    operations = [
        migrations.CreateModel(
            name='hj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
