# Generated by Django 4.1.2 on 2022-12-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_hj'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Doc',
        ),
        migrations.DeleteModel(
            name='hj',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password1',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password2',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='username',
            field=models.CharField(max_length=200),
        ),
    ]
