# Generated by Django 4.1.2 on 2022-12-17 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_docprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='email',
        ),
    ]
