# Generated by Django 4.1.2 on 2022-12-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_docprofile_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docprofile',
            old_name='name',
            new_name='address',
        ),
        migrations.AddField(
            model_name='docprofile',
            name='password',
            field=models.CharField(default='gh', max_length=100),
            preserve_default=False,
        ),
    ]
