# Generated by Django 4.1.2 on 2022-12-18 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='docprofile',
            name='regi',
            field=models.CharField(default='great', max_length=100),
            preserve_default=False,
        ),
    ]
