# Generated by Django 4.1.2 on 2022-12-18 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_docprofile_regi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docprofile',
            name='regi',
        ),
    ]
